### PR TITLE
rgb2luv,letterbox,swizzle

### PR DESCRIPTION
**Pull request by headupinclouds**
* rgb2luv colorspace conversion
* letterbox effect (cinema style)
* single texture swizzle shader
* update unit tests
* clang-format update
* bump version to 0.2.2

### CODE REVIEW

**Comment by headupinclouds** [comment]
Moved #24 to upstream repository.

**Review by ruslo — APPROVED** [review]

**Comment by headupinclouds** [comment]
Moving the PR here seems to fix the cache update.  It might be easiest to just force a valid error code from the upload script, so we can opportunistically update the cache when the PR Is local.  That way the project can still accept a PR from a fork.

**Comment by ruslo** [comment]
>  It might be easiest to just force a valid error code from the upload script

I expect uploading script do upload files and return error if for some reason upload didn't happened.

> That way the project can still accept a PR from a fork

To relax upload requirement we need to deduce the fact that pull request come from fork. Not sure if it's possible, need to check this page:
* https://docs.travis-ci.com/user/environment-variables/

**Comment by headupinclouds** [comment]
> To relax upload requirement we need to deduce the fact that pull request come from fork. Not sure if it's possible, need to check this page:

I don't see any direct way to do this, but one possibility comes from the fact that encrypted variables are not available to PR's from forks:

> Encrypted environment variables are not available to pull requests from forks due to the security risk of exposing such information to unknown code.

```
if [ ! -z "${PR_IS_NOT_A_FORK}" ] ; then do_upload; fi
```

**Pull request merged**
